# Generated by Django 3.1.2 on 2020-12-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0003_studentcourse_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, choices=[('fl', 'Florida')], max_length=2, verbose_name='State')),
                ('course_required', models.PositiveSmallIntegerField(choices=[(0, 'Always'), (1, 'Never'), (2, 'Unclear'), (3, 'Not for uncontested'), (4, 'Not always')], default=0, verbose_name='Course Required')),
                ('approval_authority', models.PositiveSmallIntegerField(choices=[(0, 'State'), (1, 'County'), (2, 'Judge'), (3, 'None')], default=0, verbose_name='Approval Authority')),
                ('course_requirements', models.PositiveSmallIntegerField(choices=[(0, 'Yes'), (1, 'None'), (2, 'Unknown')], default=0, verbose_name='Course Requirements')),
                ('developing_course', models.PositiveSmallIntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Maybe')], default=0, verbose_name='Developing Course')),
                ('dev_priority', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, verbose_name='Dev Priority')),
                ('researcher', models.TextField(blank=True, max_length=2048, verbose_name='Researcher')),
                ('research_assigned', models.DateField(blank=True, verbose_name='Research Assigned')),
                ('research_status', models.PositiveSmallIntegerField(choices=[(0, 'Completed'), (1, 'Not completed'), (2, 'In progress')], default=0, verbose_name='Research Status')),
                ('course_creator', models.TextField(blank=True, max_length=2048, verbose_name='Course Creator')),
                ('course_creation_assigned', models.DateField(blank=True, verbose_name='Course Creation Assigned')),
                ('new_modules_needed', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '5+')], default=0, verbose_name='New Modules Needed')),
                ('modules_to_edit', models.TextField(blank=True, max_length=10240, verbose_name='Modules to Edit')),
                ('course_dev_status', models.PositiveSmallIntegerField(choices=[(0, 'Completed'), (1, 'Not completed'), (2, 'In progress')], default=0, verbose_name='Course Dev Status')),
                ('translator', models.TextField(blank=True, max_length=2048, verbose_name='Translator')),
                ('translation_assigned', models.DateField(blank=True, verbose_name='Translation Assigned')),
                ('translation_status', models.PositiveSmallIntegerField(choices=[(0, 'Completed'), (1, 'Not completed'), (2, 'In progress'), (3, 'N/A'), (4, 'Not Yey')], default=0, verbose_name='Translation Status')),
                ('english_published', models.PositiveSmallIntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Pending')], default=0, verbose_name='English Published')),
                ('spanish_published', models.PositiveSmallIntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'Pending')], default=0, verbose_name='Spanish Published')),
                ('our_price', models.PositiveIntegerField(default=0, verbose_name='Our Price')),
                ('high_competitor', models.PositiveIntegerField(default=0, verbose_name='High Competitor')),
                ('low_competitor', models.PositiveIntegerField(default=0, verbose_name='Low Competitor')),
            ],
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='case_id',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Case ID'),
        ),
    ]
