# Generated by Django 3.1.2 on 2020-12-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0004_auto_20201209_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemanager',
            name='course_creation_assigned',
            field=models.DateField(blank=True, null=True, verbose_name='Course Creation Assigned'),
        ),
        migrations.AlterField(
            model_name='coursemanager',
            name='course_creator',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='Course Creator'),
        ),
        migrations.AlterField(
            model_name='coursemanager',
            name='modules_to_edit',
            field=models.TextField(blank=True, max_length=10240, null=True, verbose_name='Modules to Edit'),
        ),
        migrations.AlterField(
            model_name='coursemanager',
            name='research_assigned',
            field=models.DateField(blank=True, null=True, verbose_name='Research Assigned'),
        ),
        migrations.AlterField(
            model_name='coursemanager',
            name='researcher',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='Researcher'),
        ),
        migrations.AlterField(
            model_name='coursemanager',
            name='translation_assigned',
            field=models.DateField(blank=True, null=True, verbose_name='Translation Assigned'),
        ),
        migrations.AlterField(
            model_name='coursemanager',
            name='translator',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='Translator'),
        ),
    ]
