# Generated by Django 3.1.2 on 2020-12-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0005_auto_20201209_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Not yet contacted'), (1, 'Interested'), (2, 'Not interested'), (3, 'In process'), (4, 'Active'), (5, 'Inactive')], default=0, verbose_name='Status')),
                ('name', models.TextField(max_length=1024, verbose_name='Affiliate Name')),
                ('affiliate_type', models.PositiveSmallIntegerField(choices=[(0, 'Attorney'), (1, 'Non - attorney'), (2, 'Paralegal'), (3, 'Other')], default=0, verbose_name='Type')),
                ('monthly_case_volume', models.PositiveIntegerField(default=0, verbose_name='Monthly Case Volume')),
                ('affiliate_range', models.PositiveSmallIntegerField(choices=[(0, 'Local'), (1, 'State-wide'), (2, 'Multi-state')], default=0, verbose_name='Affiliate range')),
                ('range_state', models.TextField(blank=True, max_length=2048, null=True, verbose_name='Range State')),
                ('range_local', models.TextField(blank=True, max_length=2048, null=True, verbose_name='Range Local')),
                ('street', models.TextField(max_length=1024, verbose_name='Street')),
                ('city', models.TextField(max_length=1024, verbose_name='City')),
                ('state', models.CharField(choices=[('AK', 'ALASKA'), ('AL', 'ALABAMA'), ('AR', 'ARKANSAS'), ('AZ', 'ARIZONA'), ('CA', 'CALIFORNIA'), ('CO', 'COLORADO'), ('CT', 'CONNECTICUT'), ('DC', 'DISTRICT OF COLUMBIA'), ('DE', 'DELAWARE'), ('FL', 'FLORIDA'), ('GA', 'GEORGIA'), ('HI', 'HAWAII'), ('IA', 'IOWA'), ('ID', 'IDAHO'), ('IL', 'ILLINOIS'), ('IN', 'INDIANA'), ('KS', 'KANSAS'), ('KY', 'KENTUCKY'), ('LA', 'LOUISIANA'), ('MA', 'MASSACHUSETTS'), ('MD', 'MARYLAND'), ('ME', 'MAINE'), ('MI', 'MICHIGAN'), ('MN', 'MINNESOTA'), ('MO', 'MISSOURI'), ('MS', 'MISSISSIPPI'), ('MT', 'MONTANA'), ('NC', 'NORTH CAROLINA'), ('ND', 'NORTH DAKOTA'), ('NE', 'NEBRASKA'), ('NH', 'NEW HAMPSHIRE'), ('NJ', 'NEW JERSEY'), ('NM', 'NEW MEXICO'), ('NV', 'NEVADA'), ('NY', 'NEW YORK'), ('OH', 'OHIO'), ('OK', 'OKLAHOMA'), ('OR', 'OREGON'), ('PA', 'PENNSYLVANIA'), ('RI', 'RHODE ISLAND'), ('SC', 'SOUTH CAROLINA'), ('SD', 'SOUTH DAKOTA'), ('TN', 'TENNESSEE'), ('TX', 'TEXAS'), ('UT', 'UTAH'), ('VA', 'VIRGINIA'), ('VT', 'VERMONT'), ('WA', 'WASHINGTON'), ('WI', 'WISCONSIN'), ('WV', 'WEST VIRGINIA'), ('WY', 'WYOMING')], max_length=2, verbose_name='State')),
                ('zip', models.PositiveSmallIntegerField(default=0, verbose_name='ZIP')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('website', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Website')),
                ('poc_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='POC Phone')),
                ('poc_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='POC Email')),
                ('last_contact', models.DateField(blank=True, null=True, verbose_name='Last Contact')),
                ('last_contact_method', models.PositiveSmallIntegerField(choices=[(0, 'Email'), (1, 'Phone'), (2, 'Mail'), (3, 'Other')], default=0, verbose_name='Last Contact Method')),
                ('last_contacted_by', models.TextField(blank=True, max_length=2048, null=True, verbose_name='Last Contacted by')),
                ('last_contact_result', models.PositiveSmallIntegerField(choices=[(0, 'No response'), (1, 'No answer'), (2, 'Answered phone'), (3, 'Emailed reply')], default=0, verbose_name='Last Contact Result')),
                ('follow_up_target', models.DateField(blank=True, null=True, verbose_name='Follow up target')),
                ('comments', models.TextField(blank=True, max_length=10240, null=True, verbose_name='Comments')),
            ],
        ),
        migrations.AlterField(
            model_name='coursemanager',
            name='state',
            field=models.CharField(blank=True, choices=[('AK', 'ALASKA'), ('AL', 'ALABAMA'), ('AR', 'ARKANSAS'), ('AZ', 'ARIZONA'), ('CA', 'CALIFORNIA'), ('CO', 'COLORADO'), ('CT', 'CONNECTICUT'), ('DC', 'DISTRICT OF COLUMBIA'), ('DE', 'DELAWARE'), ('FL', 'FLORIDA'), ('GA', 'GEORGIA'), ('HI', 'HAWAII'), ('IA', 'IOWA'), ('ID', 'IDAHO'), ('IL', 'ILLINOIS'), ('IN', 'INDIANA'), ('KS', 'KANSAS'), ('KY', 'KENTUCKY'), ('LA', 'LOUISIANA'), ('MA', 'MASSACHUSETTS'), ('MD', 'MARYLAND'), ('ME', 'MAINE'), ('MI', 'MICHIGAN'), ('MN', 'MINNESOTA'), ('MO', 'MISSOURI'), ('MS', 'MISSISSIPPI'), ('MT', 'MONTANA'), ('NC', 'NORTH CAROLINA'), ('ND', 'NORTH DAKOTA'), ('NE', 'NEBRASKA'), ('NH', 'NEW HAMPSHIRE'), ('NJ', 'NEW JERSEY'), ('NM', 'NEW MEXICO'), ('NV', 'NEVADA'), ('NY', 'NEW YORK'), ('OH', 'OHIO'), ('OK', 'OKLAHOMA'), ('OR', 'OREGON'), ('PA', 'PENNSYLVANIA'), ('RI', 'RHODE ISLAND'), ('SC', 'SOUTH CAROLINA'), ('SD', 'SOUTH DAKOTA'), ('TN', 'TENNESSEE'), ('TX', 'TEXAS'), ('UT', 'UTAH'), ('VA', 'VIRGINIA'), ('VT', 'VERMONT'), ('WA', 'WASHINGTON'), ('WI', 'WISCONSIN'), ('WV', 'WEST VIRGINIA'), ('WY', 'WYOMING')], max_length=2, verbose_name='State'),
        ),
    ]
