# Generated by Django 3.1.2 on 2020-12-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0006_auto_20201210_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliatemanager',
            name='zip',
            field=models.PositiveIntegerField(default=0, verbose_name='ZIP'),
        ),
    ]
