# Generated by Django 3.1.2 on 2020-12-11 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cert', '0007_auto_20201210_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliatemanager',
            name='last_contacted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to=settings.AUTH_USER_MODEL, verbose_name='Last Contacted by'),
        ),
        migrations.AlterField(
            model_name='coursemanager',
            name='translation_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Completed'), (1, 'Not completed'), (2, 'In progress'), (3, 'N/A'), (4, 'Not Yet')], default=0, verbose_name='Translation Status'),
        ),
    ]
