# Generated by Django 3.1.2 on 2021-01-06 16:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0008_auto_20201211_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatemanager',
            name='range_states',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('AK', 'ALASKA'), ('AL', 'ALABAMA'), ('AR', 'ARKANSAS'), ('AZ', 'ARIZONA'), ('CA', 'CALIFORNIA'), ('CO', 'COLORADO'), ('CT', 'CONNECTICUT'), ('DC', 'DISTRICT OF COLUMBIA'), ('DE', 'DELAWARE'), ('FL', 'FLORIDA'), ('GA', 'GEORGIA'), ('HI', 'HAWAII'), ('IA', 'IOWA'), ('ID', 'IDAHO'), ('IL', 'ILLINOIS'), ('IN', 'INDIANA'), ('KS', 'KANSAS'), ('KY', 'KENTUCKY'), ('LA', 'LOUISIANA'), ('MA', 'MASSACHUSETTS'), ('MD', 'MARYLAND'), ('ME', 'MAINE'), ('MI', 'MICHIGAN'), ('MN', 'MINNESOTA'), ('MO', 'MISSOURI'), ('MS', 'MISSISSIPPI'), ('MT', 'MONTANA'), ('NC', 'NORTH CAROLINA'), ('ND', 'NORTH DAKOTA'), ('NE', 'NEBRASKA'), ('NH', 'NEW HAMPSHIRE'), ('NJ', 'NEW JERSEY'), ('NM', 'NEW MEXICO'), ('NV', 'NEVADA'), ('NY', 'NEW YORK'), ('OH', 'OHIO'), ('OK', 'OKLAHOMA'), ('OR', 'OREGON'), ('PA', 'PENNSYLVANIA'), ('RI', 'RHODE ISLAND'), ('SC', 'SOUTH CAROLINA'), ('SD', 'SOUTH DAKOTA'), ('TN', 'TENNESSEE'), ('TX', 'TEXAS'), ('UT', 'UTAH'), ('VA', 'VIRGINIA'), ('VT', 'VERMONT'), ('WA', 'WASHINGTON'), ('WI', 'WISCONSIN'), ('WV', 'WEST VIRGINIA'), ('WY', 'WYOMING')], max_length=152, null=True, verbose_name='Range State'),
        ),
    ]
