# Generated by Django 3.1.2 on 2021-01-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0009_affiliatemanager_range_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliatemanager',
            name='city',
            field=models.CharField(max_length=1024, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='affiliatemanager',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='Affiliate Name'),
        ),
        migrations.AlterField(
            model_name='affiliatemanager',
            name='range_local',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Range Local'),
        ),
        migrations.AlterField(
            model_name='affiliatemanager',
            name='range_state',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Range State'),
        ),
        migrations.AlterField(
            model_name='affiliatemanager',
            name='street',
            field=models.CharField(max_length=1024, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='affiliatemanager',
            name='website',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='coursemanager',
            name='course_creator',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Course Creator'),
        ),
        migrations.AlterField(
            model_name='coursemanager',
            name='researcher',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Researcher'),
        ),
        migrations.AlterField(
            model_name='coursemanager',
            name='translator',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Translator'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(default='', max_length=128, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=128, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
    ]
